[package]
name = "ccs811"
version = "0.1.0"
authors = ["mmmpa <mmmpa.mmmpa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.31"
tokio = { version = "0.2", features = ["process", "sync", "macros", "time", "fs"] }
futures = "0.3.5"
log = "0.4.11"
nix = "0.17.0"
pretty_env_logger = "0.4"

rusoto_core = "0.45.0"
rusoto_dynamodb = "0.45.0"
rusoto_credential = "0.45.0"

openssl = { version = "0.10", features = ["vendored"] }


chrono = "0.4.13"
chrono-tz = "0.5.2"
serde = "1.0.114"
serde_json = "1.0.56"
